Added Hover effect
pranjay-poddar/Swasthify pull request #87
Opened 2022-10-06 08:16 UTC by Rituraj-13

# Title and Issue number 
Issue no #84 
Link of the issue :- [Click Here](https://github.com/pranjay-poddar/Swasthify/issues/84)

Close #84 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2022-10-06 10:00 UTC, Rituraj-13 commented
Hey @pranjay-poddar, I have made the changes. Kindly have a look.

2022-10-06 18:27 UTC, pranjay-poddar requested changes
there is a bug on clicking hospital login due to the blue background which makes it hard to read and reduces visibility, which is not the aim of the issue also after clicking about us the blue background and hover are not retained. hope you will work on fixing this

2022-10-06 18:35 UTC, Rituraj-13 commented
> there is a bug on clicking hospital login due to the blue background which makes it hard to read and reduces visibility, which is not the aim of the issue also after clicking about us the blue background and hover are not retained. hope you will work on fixing this

Okay, I will made the changes accordingly 👍

2022-10-08 09:15 UTC, pranjay-poddar approved these changes

2022-10-08 09:15 UTC, merged